version: "3"

services:
  postgres:
    image: "postgres:9.4"
    ports:
      - "5432:5432"
  zappr:
    build: .
    container_name: zappr-app
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    ports:
      - "3000:3000"
      - "3003:3003"
    environment:
      - LOG_LEVEL=debug
      - DB_HOST=postgres
      - NODE_ENV=development
      - HOST_ADDR
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
